//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class bigeyedev_logic_address
    {
        public int id { get; set; }
        public Nullable<int> logic_id { get; set; }
        public string sub_district { get; set; }
        public string district { get; set; }
        public string province { get; set; }
        public string zip { get; set; }
        public string mobile { get; set; }
        public string mobile2 { get; set; }
        public string mobile3 { get; set; }
    }
}
