//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class bigeyedev_brand
    {
        public int id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> brand_group { get; set; }
        public Nullable<int> visible { get; set; }
        public string brand { get; set; }
        public string logo_url { get; set; }
        public string fashion_bgcolor { get; set; }
    }
}
