//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class bigeyedev_shop
    {
        public int id { get; set; }
        public int shop_id { get; set; }
        public string shop_name { get; set; }
        public string promotion { get; set; }
        public string logo_menu_url { get; set; }
        public string logo_top_url { get; set; }
        public string meta_des { get; set; }
        public string meta_keyword { get; set; }
        public string website { get; set; }
        public string tel { get; set; }
        public string face_id { get; set; }
        public string face_qr_url { get; set; }
        public string face_url { get; set; }
        public string line_id { get; set; }
        public string line_qr_url { get; set; }
        public string line_url { get; set; }
        public string line_at_id { get; set; }
        public string insta_id { get; set; }
        public string insta_qr_url { get; set; }
        public string insta_url { get; set; }
        public string email { get; set; }
        public string location_address { get; set; }
        public string location_url { get; set; }
    }
}
