//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class bigeyedev_free
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> free_box { get; set; }
        public Nullable<float> delivery_fee { get; set; }
        public Nullable<int> acrylic { get; set; }
        public Nullable<int> stand_sw { get; set; }
        public string album { get; set; }
        public Nullable<int> bag { get; set; }
        public Nullable<int> manual { get; set; }
        public Nullable<int> cd { get; set; }
        public Nullable<int> certi { get; set; }
        public Nullable<int> desktop { get; set; }
        public Nullable<int> poster { get; set; }
        public Nullable<int> vinyl { get; set; }
        public Nullable<int> free_solution { get; set; }
        public Nullable<int> vinyl_big { get; set; }
        public Nullable<int> acrylic_tray { get; set; }
        public Nullable<int> stand_pd { get; set; }
    }
}
