//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sugareyeEntities : DbContext
    {
        public sugareyeEntities()
            : base("name=sugareyeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<order_power_item> order_power_item { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<set_power_volume> set_power_volume { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
