//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string model { get; set; }
        public string type { get; set; }
        public Nullable<int> brand_order { get; set; }
        public string brand { get; set; }
        public Nullable<int> black { get; set; }
        public Nullable<int> choco { get; set; }
        public Nullable<int> gray { get; set; }
        public Nullable<int> brown { get; set; }
        public Nullable<int> blue { get; set; }
        public Nullable<int> green { get; set; }
        public Nullable<int> violet { get; set; }
        public Nullable<int> pink { get; set; }
        public Nullable<int> silver { get; set; }
        public Nullable<int> gold { get; set; }
        public Nullable<int> sky { get; set; }
        public Nullable<int> red { get; set; }
        public string near { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> price_s { get; set; }
    }
}
