//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> status_print { get; set; }
        public Nullable<int> have_fashion { get; set; }
        public Nullable<int> have_power { get; set; }
        public string name { get; set; }
        public string shop_name { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public string area { get; set; }
        public string province { get; set; }
        public string zip { get; set; }
        public string mobile { get; set; }
        public string mobile2 { get; set; }
        public string line_id { get; set; }
        public string line_display { get; set; }
        public string email { get; set; }
        public string note { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note_power { get; set; }
        public string note_power2 { get; set; }
        public string note_power3 { get; set; }
        public Nullable<int> fix_volume { get; set; }
        public Nullable<int> fix_power_volume { get; set; }
        public Nullable<int> eyeberry_sum_volume { get; set; }
        public Nullable<int> sweety_sum_volume { get; set; }
        public Nullable<int> lollipop_sum_volume { get; set; }
        public Nullable<int> prettydoll_sum_volume { get; set; }
        public Nullable<int> dream_sum_volume { get; set; }
        public Nullable<int> kitty_sum_volume { get; set; }
        public Nullable<int> pretty_sum_volume { get; set; }
        public Nullable<int> beauty_sum_volume { get; set; }
        public Nullable<int> all_sum_volume { get; set; }
        public Nullable<int> all_sum_power_volume { get; set; }
        public Nullable<int> total_volume { get; set; }
        public string user { get; set; }
        public Nullable<int> eyeberry_volume { get; set; }
        public Nullable<int> sweety_volume { get; set; }
        public Nullable<int> lollipop_volume { get; set; }
        public Nullable<int> prettydoll_volume { get; set; }
        public Nullable<int> dream_volume { get; set; }
        public Nullable<int> kitty_volume { get; set; }
        public Nullable<int> pretty_volume { get; set; }
        public Nullable<int> beauty_volume { get; set; }
        public string pay_bank { get; set; }
        public string pay_date { get; set; }
        public string pay_time { get; set; }
        public Nullable<float> pay_amount { get; set; }
        public Nullable<int> pay_finish { get; set; }
        public Nullable<float> eyeberry_price { get; set; }
        public Nullable<float> sweety_price { get; set; }
        public Nullable<float> lollipop_price { get; set; }
        public Nullable<float> prettydoll_price { get; set; }
        public Nullable<float> dream_price { get; set; }
        public Nullable<float> kitty_price { get; set; }
        public Nullable<float> pretty_price { get; set; }
        public Nullable<float> beauty_price { get; set; }
    }
}
