//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_power_item
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> group_brand { get; set; }
        public Nullable<int> brand_order { get; set; }
        public string brand { get; set; }
        public string color { get; set; }
        public Nullable<int> power { get; set; }
        public string model { get; set; }
        public Nullable<int> volume { get; set; }
        public string near { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> price_s { get; set; }
    }
}
