//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_power_volume
    {
        public int id { get; set; }
        public string brand { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<int> want_black { get; set; }
        public Nullable<int> want_choco { get; set; }
        public Nullable<int> want_gray { get; set; }
        public Nullable<int> want_brown { get; set; }
        public Nullable<int> want_blue { get; set; }
        public Nullable<int> want_green { get; set; }
        public Nullable<int> want_violet { get; set; }
        public Nullable<int> want_pink { get; set; }
        public Nullable<int> want_silver { get; set; }
        public Nullable<int> want_gold { get; set; }
        public Nullable<int> want_sky { get; set; }
        public Nullable<int> want_red { get; set; }
    }
}
