//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigeyedev
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string nickname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string image { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string line { get; set; }
        public string position { get; set; }
        public string contract { get; set; }
    }
}
