//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigeye WholeSale.
        /// </summary>
        internal static string head_des {
            get {
                return ResourceManager.GetString("head_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string html_lang {
            get {
                return ResourceManager.GetString("html_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string login_email {
            get {
                return ResourceManager.GetString("login_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget your years password?.
        /// </summary>
        internal static string login_forgot {
            get {
                return ResourceManager.GetString("login_forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        internal static string login_go {
            get {
                return ResourceManager.GetString("login_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string login_line {
            get {
                return ResourceManager.GetString("login_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string login_mobile {
            get {
                return ResourceManager.GetString("login_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string login_name {
            get {
                return ResourceManager.GetString("login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string login_next {
            get {
                return ResourceManager.GetString("login_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string login_register {
            get {
                return ResourceManager.GetString("login_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years                (ex. 1983).
        /// </summary>
        internal static string login_year {
            get {
                return ResourceManager.GetString("login_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order to System.
        /// </summary>
        internal static string main_btn_cart_to_db {
            get {
                return ResourceManager.GetString("main_btn_cart_to_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order to Cart.
        /// </summary>
        internal static string main_btn_order_to_cart {
            get {
                return ResourceManager.GetString("main_btn_order_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream.
        /// </summary>
        internal static string main_tab_dream {
            get {
                return ResourceManager.GetString("main_tab_dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueba.
        /// </summary>
        internal static string main_tab_dueba {
            get {
                return ResourceManager.GetString("main_tab_dueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vassen &amp; Neo.
        /// </summary>
        internal static string main_tab_vassen {
            get {
                return ResourceManager.GetString("main_tab_vassen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string menu_cart {
            get {
                return ResourceManager.GetString("menu_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string menu_contact {
            get {
                return ResourceManager.GetString("menu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Lens.
        /// </summary>
        internal static string menu_fashion {
            get {
                return ResourceManager.GetString("menu_fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Color.
        /// </summary>
        internal static string menu_fashion_color {
            get {
                return ResourceManager.GetString("menu_fashion_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Starter.
        /// </summary>
        internal static string menu_fashion_no_select {
            get {
                return ResourceManager.GetString("menu_fashion_no_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Model.
        /// </summary>
        internal static string menu_fashion_select {
            get {
                return ResourceManager.GetString("menu_fashion_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string menu_login {
            get {
                return ResourceManager.GetString("menu_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Products.
        /// </summary>
        internal static string menu_other {
            get {
                return ResourceManager.GetString("menu_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Box.
        /// </summary>
        internal static string menu_other_setbox {
            get {
                return ResourceManager.GetString("menu_other_setbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string menu_other_solution {
            get {
                return ResourceManager.GetString("menu_other_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Lens.
        /// </summary>
        internal static string menu_power {
            get {
                return ResourceManager.GetString("menu_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Color.
        /// </summary>
        internal static string menu_power_color {
            get {
                return ResourceManager.GetString("menu_power_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Starter.
        /// </summary>
        internal static string menu_power_no_select {
            get {
                return ResourceManager.GetString("menu_power_no_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Model.
        /// </summary>
        internal static string menu_power_select {
            get {
                return ResourceManager.GetString("menu_power_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend New Product.
        /// </summary>
        internal static string menu_recommend {
            get {
                return ResourceManager.GetString("menu_recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DreamCon.
        /// </summary>
        internal static string menu_recommend_dream {
            get {
                return ResourceManager.GetString("menu_recommend_dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueba.
        /// </summary>
        internal static string menu_recommend_dueba {
            get {
                return ResourceManager.GetString("menu_recommend_dueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vassen.
        /// </summary>
        internal static string menu_recomment_vassen {
            get {
                return ResourceManager.GetString("menu_recomment_vassen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string menu_service {
            get {
                return ResourceManager.GetString("menu_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Product.
        /// </summary>
        internal static string menu_service_change {
            get {
                return ResourceManager.GetString("menu_service_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        internal static string menu_service_recommend {
            get {
                return ResourceManager.GetString("menu_service_recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string menu_tracking {
            get {
                return ResourceManager.GetString("menu_tracking", resourceCulture);
            }
        }
    }
}
